### ISSUE TITLE
Where is GroundedSAM preprocess code.

### ISSUE THREAD

**Issue by synsin0** [LinShan-Bin/OccNeRF#1]
Thanks for your great work. I'd like to query for the GroundedSAM preprocess code which I do not find as a submodule maybe?

**Comment by LinShan-Bin** [comment]
Thanks for pointing out this mistake! We've updated the code. Please check the newest version.

**Comment by synsin0** [comment]
The preprocessing tasks take take a lot of time. Would you mind upload the preprocessing results so that I may download directly?

**Comment by LinShan-Bin** [comment]
OK, we are working on this. Since the processed file is very large (~300 GB before compressing), it will take one or two days.

**Comment by LinShan-Bin** [comment]
The preprocessed data is uploaded.

**Comment by rockywind** [comment]
How can I deal this problem? ```` groundingdino_model = load_model_hf(ckpt_repo_id, ckpt_filenmae, ckpt_config_filename)
TypeError: load_model_hf() takes from 0 to 1 positional arguments but 3 were given ````
