### ISSUE TITLE
Training code for SemanticKITTI

### ISSUE THREAD

**Issue by JunjieLiuSWU** [LinShan-Bin/OccNeRF#18]
Hello, could you release the training code for SemanticKITTI?

**Comment by LinShan-Bin** [comment]
We currently do not have plans to release the code for SemanticKITTI. Our method is specifically designed for multi-camera occupancy prediction, and as such, the code is tailored for multi-camera inputs. The SemanticKITTI experiments were conducted using a different branch of our code. Releasing the SemanticKITTI code would require us to clean up this branch; however, we currently lack the GPU resources needed to verify the cleaned code.
