### ISSUE TITLE
depth training problems when set contracted_coord = False

### ISSUE THREAD

**Issue by Lazyangel** [LinShan-Bin/OccNeRF#19]
你好，感谢你们出色的工作！我希望使用更小的显存和更少的时间来训练模型，于是我设置contracted_coord = False并调整了voxels_size = [16, 200, 200]。但此时模型训练失败，验证时最小深度和最大深度差距很小，在训练一两个epoch后渲染的深度值就为同一值了。你们有遇到过这样的情况吗？面对这样的情况我该如何调整模型参数让模型能够训练？非常感谢，如果你们能够给予一些帮助！
![0-0](https://github.com/LinShan-Bin/OccNeRF/assets/59599339/812c5e9e-267d-46ab-b6a0-16d2dec9f66c)

**Comment by LinShan-Bin** [comment]
可能有两个原因，一是模型刚开始训练的时候初始深度较小，投影时全部被 mask 掉而没有投到参考图片上；二是 loss_distortion 的权重过大，可能要根据其他参数调整。可以尝试增大采样的最小距离，降低 loss_distortion 的权重。
