### ISSUE TITLE
Model complexity and inference speed (fps)

### ISSUE THREAD

**Issue by Tuhin-nd** [LinShan-Bin/OccNeRF#24]
Dear @LinShan-Bin / @weiyithu / @JunchengYan ,

Thanks for the amazing paper and GitHub repo. Could you provide some insights on the model complexity / inference fps?

**Comment by LinShan-Bin** [comment]
Thank you for your attention. The inference latency is about 180 ms (about 5 fps) on a single A100 without rendering.
