### ISSUE TITLE
2D semantic labels for nuScenes

### ISSUE THREAD

**Issue by RONGSHENG0404** [LinShan-Bin/OccNeRF#27]
The link of 2D semantic labels for nuScenes is missing, could you please offer another one?

**Comment by seamie6** [comment]
Yes. can the link be updated?

**Comment by rkdckddnjs9** [comment]
same problem

**Comment by LinShan-Bin** [comment]
I'm sorry for the mistake. The link is down because I can no longer access the former account. I will update the URL as soon as possible.

**Comment by LinShan-Bin** [comment]
Please check the new link: https://cloud.tsinghua.edu.cn/d/564c9ac19b5f4b54a774/
