### ISSUE TITLE
How to train with v1.0-mini dataset?

### ISSUE THREAD

**Issue by Terencedu** [LinShan-Bin/OccNeRF#6]
Hi, thanks for your great work! 

Because of equipment limitations, I can only train with 8GB GPU (Nivdia 4060 laptop) and v1.0-mini dataset. Metrics are not important, just want to run on my own computer.

1. I changed some hyperparameters, generated train.txt and val.txt of v1.0-mini (the first and last frames of each scene are excluded). It seem to train successfully:
input_channel: 64 -> 4
con_channel: 16 -> 1
encoder: 101 ->50
render_h: 180 ->45
render_w: 320 -> 80
![截图 2024-01-09 10-57-04](https://github.com/LinShan-Bin/OccNeRF/assets/102672687/23633654-0a0a-4c98-aa54-633bc2d06f3a)

2. Do you have some advice on training with v1.0-mini dataset?

I generate the train.txt, val.txt, and  depth of v1.0mini dataset by tools/export_gt_depth_nusc.py

Do I need to change ground truth occupancy labels in ./data/nuscenes/gts, 2D semantic labels in ./data/nuscenes/nuscenes_semantic and checkpoint in ./ckpts?

3. There are 700 training scene and 150 val scene in v1.0-full dataset, but why there are just 20096 sample tokens (about 500 scene) in your train.txt?

**Comment by LinShan-Bin** [comment]
1. The ‘train.txt’ and ‘val.txt’ are from [SurroundDepth](https://github.com/weiyithu/SurroundDepth) and only contain frames that have ‘prev’ and ‘next’ info. For mini dataset, you should use nuscenes_devkit to remove invalid frames by yourself.
2. For ground truths, no preprocessed data is available for the mini dataset so you should also generate it by yourself.
3. You don’t need to change the checkpoints for pretrained models.
4. If you want to debug with the mini dataset, just make a dummy one to match the input format.

**Comment by Terencedu** [comment]
Thank you for your reply! I would have a try.

**Comment by XiangFeng66** [comment]
@LinShan-Bin  你好，感谢你卓越的工作，在运行minidata数据时，我遇到了以下错误
KeyError: 'a593a62aa9b54234ae666f3006b4d9f5'
请问如何解决他

**Comment by XiangFeng66** [comment]
@Terencedu 你好，我在运行mini data时遇到FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes/nuscenes_depth/samples/CAM_FRONT/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402928112460.npy' 这一问题，请问您知道是什么原因导致吗，或许您能提供一下minidata的train，val.txt,以及对应的gt_depth吗
